# Numpy Prog. Assignment 8, Alexander Kyrkjeeide, Version 1, Spring 2023 

## A) 

In [7]:
import numpy as np

arr = np.array([[10, 20], [30, 40]])

squared = arr ** 2

added = arr + 100

multiplied = arr * 5

sqrt = np.sqrt(arr)

print(squared)
print(added)
print(multiplied)
print(sqrt)

[[ 100  400]
 [ 900 1600]]
[[110 120]
 [130 140]]
[[ 50 100]
 [150 200]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


## B)

In [8]:
import numpy as np

# 3-by-3 array with integers from 3 to 27 in multiples of 3
arr1 = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]])

# 3-by-3 array with elements evenly spaced between 10 and 20
arr2 = np.linspace(10, 20, 9).reshape(3,3)

#Adding them together 
result = arr1 * arr2

print(result)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


## C)

In [13]:
import numpy as np

# Load the five .npy files into NumPy arrays
arr1 = np.load('process1.npy')
arr2 = np.load('process2.npy')
arr3 = np.load('process3.npy')
arr4 = np.load('process4.npy')
arr5 = np.load('process5.npy')

# Stack the five arrays into a 5-by-5 array
data = np.stack([arr1, arr2, arr3, arr4, arr5], axis=1)


mean_data = np.mean(data, axis=0)


print("Mean of each column of data:")
print(mean_data)

Mean of each column of data:
[[52. 12. 81.  0. 58.]
 [96.  4. 61. 16. 43.]
 [38. 96. 45. 17. 58.]
 [97. 21. 22. 25.  6.]
 [77.  6. 19.  2. 74.]]
